import frappe

from vietnam_compliance.vat_vietnam.constants import (
    EINVOICE_STATUS_CHOICES,
    PROVINCE_CHOICES,
)

CUSTOM_FIELDS = {
    "Sales Invoice": [
        {
            "fieldname": "einvoice_section",
            "label": "Hóa đơn điện tử",
            "fieldtype": "Section Break",
            "insert_after": "company",
        },
        {
            "fieldname": "einvoice_status",
            "label": "Trạng thái HĐĐT",
            "fieldtype": "Select",
            "insert_after": "einvoice_section",
            "options": EINVOICE_STATUS_CHOICES,
            "read_only": 1,
            "no_copy": 1,
            "translatable": 0,
        },
        {
            "fieldname": "transaction_id",
            "label": "Mã tra cứu",
            "fieldtype": "Data",
            "read_only": 1,
            "insert_after": "einvoice_status",
            "no_copy": 1,
            "translatable": 0,
        },
        {
            "fieldname": "invoice_form_number",
            "label": "Mẫu số HĐ",
            "fieldtype": "Select",
            "insert_after": "transaction_id",
            "options": "01GTKT0/001\n01GTKT0/002\n02GTTT0/001\n02GTTT0/002",
            "translatable": 0,
        },
        {
            "fieldname": "invoice_series",
            "label": "Ký hiệu",
            "fieldtype": "Data",
            "insert_after": "invoice_form_number",
            "translatable": 0,
            "description": "Ký hiệu hóa đơn (VD: AA/23E)",
        },
        {
            "fieldname": "adjustment_type",
            "label": "Loại điều chỉnh",
            "fieldtype": "Select",
            "insert_after": "invoice_series",
            "options": "\nĐiều chỉnh\nThay thế\nHủy",
            "translatable": 0,
            "depends_on": "eval:doc.is_return",
        },
        {
            "fieldname": "adjusted_invoice",
            "label": "Hóa đơn gốc",
            "fieldtype": "Link",
            "insert_after": "adjustment_type",
            "options": "Sales Invoice",
            "depends_on": 'eval:["Điều chỉnh","Thay thế"].includes(doc.adjustment_type)',
            "translatable": 0,
        },
        {
            "fieldname": "gdt_submitted_on",
            "label": "Ngày gửi CQT",
            "fieldtype": "Datetime",
            "read_only": 1,
            "insert_after": "adjusted_invoice",
            "no_copy": 1,
            "translatable": 0,
        },
        {
            "fieldname": "gdt_response",
            "label": "Phản hồi CQT",
            "fieldtype": "Code",
            "read_only": 1,
            "insert_after": "gdt_submitted_on",
            "no_copy": 1,
            "translatable": 0,
            "hidden": 1,
        },
        {
            "fieldname": "einvoice_qr_section",
            "fieldtype": "Section Break",
            "insert_after": "gdt_response",
        },
        {
            "fieldname": "einvoice_qr_image",
            "label": "Mã QR tra cứu",
            "fieldtype": "Attach Image",
            "read_only": 1,
            "insert_after": "einvoice_qr_section",
            "no_copy": 1,
            "translatable": 0,
        },
    ],
    "Company": [
        {
            "fieldname": "tax_info_section",
            "label": "Thông tin thuế",
            "fieldtype": "Section Break",
            "insert_after": "company_logo",
        },
        {
            "fieldname": "mst",
            "label": "Mã số thuế (MST)",
            "fieldtype": "Data",
            "insert_after": "tax_info_section",
            "length": 13,
            "translatable": 0,
        },
        {
            "fieldname": "digital_certificate_ref",
            "label": "Chứng thư số",
            "fieldtype": "Data",
            "insert_after": "mst",
            "description": "Mã tham chiếu chứng thư số (USB Token / HSM)",
            "translatable": 0,
        },
        {
            "fieldname": "gdt_credentials_section",
            "fieldtype": "Section Break",
            "insert_after": "digital_certificate_ref",
            "label": "Tài khoản Cổng Dịch vụ Thuế",
        },
        {
            "fieldname": "gdt_username",
            "label": "Tên đăng nhập CQT",
            "fieldtype": "Data",
            "insert_after": "gdt_credentials_section",
            "translatable": 0,
        },
        {
            "fieldname": "gdt_password",
            "label": "Mật khẩu CQT",
            "fieldtype": "Password",
            "insert_after": "gdt_username",
            "translatable": 0,
        },
        {
            "fieldname": "default_einvoice_type",
            "label": "Loại HĐĐT mặc định",
            "fieldtype": "Select",
            "insert_after": "gdt_password",
            "options": "Có mã CQT\nKhông mã CQT",
            "default": "Có mã CQT",
            "translatable": 0,
        },
    ],
    "Customer": [
        {
            "fieldname": "tax_info_section",
            "label": "Thông tin thuế",
            "fieldtype": "Section Break",
            "insert_after": "customer_details",
        },
        {
            "fieldname": "mst",
            "label": "Mã số thuế (MST)",
            "fieldtype": "Data",
            "insert_after": "tax_info_section",
            "length": 13,
            "translatable": 0,
        },
        {
            "fieldname": "buyer_id_type",
            "label": "Loại giấy tờ",
            "fieldtype": "Select",
            "insert_after": "mst",
            "options": "\nCMND/CCCD\nHộ chiếu\nGiấy phép ĐKKD",
            "translatable": 0,
        },
        {
            "fieldname": "buyer_id_number",
            "label": "Số giấy tờ",
            "fieldtype": "Data",
            "insert_after": "buyer_id_type",
            "translatable": 0,
        },
    ],
    "Supplier": [
        {
            "fieldname": "tax_info_section",
            "label": "Thông tin thuế",
            "fieldtype": "Section Break",
            "insert_after": "supplier_details",
        },
        {
            "fieldname": "mst",
            "label": "Mã số thuế (MST)",
            "fieldtype": "Data",
            "insert_after": "tax_info_section",
            "length": 13,
            "translatable": 0,
        },
    ],
    "Address": [
        {
            "fieldname": "province",
            "label": "Tỉnh/Thành phố",
            "fieldtype": "Select",
            "insert_after": "country",
            "options": PROVINCE_CHOICES,
            "translatable": 0,
        },
    ],
}

E_INVOICE_FIELDS = {
    "Sales Invoice": [
        {
            "fieldname": "einvoice_status",
            "label": "Trạng thái HĐĐT",
            "fieldtype": "Select",
            "insert_after": "status",
            "options": EINVOICE_STATUS_CHOICES,
            "default": None,
            "hidden": 1,
            "no_copy": 1,
            "print_hide": 1,
            "read_only": 1,
            "translatable": 1,
        },
    ]
}
